cd /home/thuy0050/code/tevatron/src/tevatron/louis/scripts/rag

MODEL="gte"
DATA_NAME="temporal_nobel_prize"
MODEL_NAME="mrl"
LORA="--lora"
FLASHRAG_CONFIG="/home/thuy0050/code/tevatron/src/tevatron/louis/scripts/rag/configs/qwen8b.yaml"

### Original Data ### 
EXP_NAME="original_data"

MATRYOSHKA_DIM="64"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

MATRYOSHKA_DIM="128"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

MATRYOSHKA_DIM="256"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

MATRYOSHKA_DIM="512"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

MATRYOSHKA_DIM="768"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

# MATRYOSHKA_DIM="1024"
# sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

### Our Data ### 
EXP_NAME="our_data"

MATRYOSHKA_DIM="64"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

MATRYOSHKA_DIM="128"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

MATRYOSHKA_DIM="256"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

MATRYOSHKA_DIM="512"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

MATRYOSHKA_DIM="768"
sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"

# MATRYOSHKA_DIM="1024"
# sbatch rag.sh "$MODEL" "$DATA_NAME" "$MODEL_NAME" "$EXP_NAME" "$LORA" "$MATRYOSHKA_DIM" "$FLASHRAG_CONFIG"