configs = {
    "bge": dict(
        checkpoint="BAAI/bge-base-en-v1.5",
        pooling="cls",
        query_prefix="'Represent this sentence for searching relevant passages: '",
        passage_prefix="''",
        query_prompts="'Represent this sentence for searching relevant passages: '",
        corpus_prompts="''",
        normalize="--normalize",
        padding_side="right",
        adaptor_dim="768",
        matryoshka_dim="768",
        matryoshka_dim_list=[64, 128, 256, 512, 768],
        temperature="0.02",
    ),
    "bgem3": dict(
        checkpoint="BAAI/bge-m3",
        pooling="cls",
        query_prefix="''",
        passage_prefix="''",
        query_prompts="''",
        corpus_prompts="''",
        normalize="--normalize",
        padding_side="right",
        adaptor_dim="1024",
        matryoshka_dim="1024",
        matryoshka_dim_list=[64, 128, 256, 512, 768, 1024],
        temperature="0.02",
    ),
    "contriever": dict(
        checkpoint="facebook/contriever",
        pooling="mean",
        query_prefix="''",
        passage_prefix="''",
        query_prompts="''",
        corpus_prompts="''",
        normalize="",
        padding_side="right",
        adaptor_dim="768",
        matryoshka_dim="768",
        matryoshka_dim_list=[64, 768], # [64, 128, 256, 512, 768],
        temperature="0.05",
    ),
    "gte": dict(
        checkpoint="thenlper/gte-base",
        pooling="mean",
        query_prefix="''",
        passage_prefix="''",
        query_prompts="''",
        corpus_prompts="''",
        normalize="--normalize",
        padding_side="right",
        adaptor_dim="768",
        matryoshka_dim="768",
        matryoshka_dim_list=[64, 128, 256, 512, 768],
        temperature="0.02",
    ),
    "gte1.5": dict(
        checkpoint="Alibaba-NLP/gte-base-en-v1.5",
        pooling="cls",
        query_prefix="''",
        passage_prefix="''",
        query_prompts="''",
        corpus_prompts="''",
        normalize="--normalize",
        padding_side="right",
        adaptor_dim="768",
        matryoshka_dim="768",
        matryoshka_dim_list=[64, 128, 256, 512, 768],
        temperature="0.02",
    ),
    "nomic": dict(
        checkpoint="nomic-ai/nomic-embed-text-v1.5",
        pooling="mean",
        query_prefix="search_query:",
        passage_prefix="search_document:",
        query_prompts="search_query:",
        corpus_prompts="search_document:",
        normalize="--normalize",
        padding_side="right",
        adaptor_dim="768",
        matryoshka_dim="768",
        matryoshka_dim_list=[64, 128, 256, 512, 768],
        temperature="0.02",
    ),
    "qwen3": dict(
        checkpoint="Qwen/Qwen3-Embedding-0.6B",
        pooling="last",
        query_prefix="'Instruct: Given a web search query, retrieve relevant passages that answer the query\\nQuery:'",
        passage_prefix="''",
        query_prompts="'Instruct: Given a web search query, retrieve relevant passages that answer the query\\nQuery:'",
        corpus_prompts="''",
        normalize="--normalize",
        padding_side="left",
        adaptor_dim="1024",
        matryoshka_dim="1024",
        matryoshka_dim_list=[64, 128, 256, 512, 768, 1024],
        temperature="0.02",
    ),
}

